name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build binaries
      run: |
        # Build for Linux amd64
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o keyphy-linux-amd64 ./cmd/keyphy
        
        # Build for Linux arm64
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o keyphy-linux-arm64 ./cmd/keyphy
        
        # Create archives
        tar -czf keyphy-linux-amd64.tar.gz keyphy-linux-amd64
        tar -czf keyphy-linux-arm64.tar.gz keyphy-linux-arm64
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          keyphy-linux-amd64.tar.gz
          keyphy-linux-arm64.tar.gz
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}